config:
  backup: true
  banner: false
  create: true
  dotpath: ~/.dotfiles/user
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
dotfiles:
  d_blender:
    src: config/blender
    dst: ~/.config/blender
    cmpignore:
      - '*'
      - '!*.blend'
      - '*/scripts/**'
    upignore:
      - '*'
      - '!*.blend'
      - '*/scripts/**'
  d_btop:
    src: config/btop
    dst: ~/.config/btop
    upignore:
      - btop.log
    cmpignore:
      - btop.log
  d_config_oh-my-zsh_plugins:
    src: config/oh-my-zsh/plugins
    dst: ~/.config/oh-my-zsh/plugins
    link: link_children
  d_config_oh-my-zsh_themes:
    src: config/oh-my-zsh/themes
    dst: ~/.config/oh-my-zsh/themes
    link: link_children
  d_gtk-2.0:
    src: config/gtk-2.0
    dst: ~/.config/gtk-2.0
    chmod: '700'
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_gtklock:
    src: config/gtklock
    dst: ~/.config/gtklock
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
  d_local_share_ulauncher_extensions:
    src: local/share/ulauncher/extensions
    dst: ~/.local/share/ulauncher/extensions
    link: link_children
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.local/share/oh-my-zsh
    link: absolute
  d_openrgb:
    src: config/OpenRGB
    dst: ~/.config/OpenRGB
    upignore:
      - logs/*
    cmpignore:
      - logs/*
  d_plugged:
    src: vim/plugged
    dst: ~/.vim/plugged
    link: link_children
  d_qt5ct:
    src: config/qt5ct
    dst: ~/.config/qt5ct
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_systemd:
    src: config/systemd
    dst: ~/.config/systemd
    upignore:
      - '*.wants'
    cmpignore:
      - '*.wants'
  d_ulauncher:
    src: config/ulauncher
    dst: ~/.config/ulauncher
    upignore:
      - user-themes/*
    cmpignore:
      - user-themes/*
  d_ulauncher_themes:
    src: config/ulauncher/user-themes
    dst: ~/.config/ulauncher/user-themes
    link: link_children
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_xfce4:
    src: config/xfce4
    dst: ~/.config/xfce4
    chmod: '700'
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    upignore:
      - .zcompdump
    cmpignore:
      - .zcompdump
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_code-flags.conf:
    src: config/code-flags.conf
    dst: ~/.config/code-flags.conf
  f_config:
    src: config/swayidle/config
    dst: ~/.config/swayidle/config
  f_config.conf:
    src: config/neofetch/config.conf
    dst: ~/.config/neofetch/config.conf
  f_config.json:
    src: config/swaync/config.json
    dst: ~/.config/swaync/config.json
  f_dmrc:
    src: dmrc
    dst: ~/.dmrc
  f_electron-flags.conf:
    src: config/electron-flags.conf
    dst: ~/.config/electron-flags.conf
  f_electron13-flags.conf:
    src: config/electron13-flags.conf
    dst: ~/.config/electron13-flags.conf
  f_extract-audio-streams:
    src: local/bin/extract-audio-streams
    dst: ~/.local/bin/extract-audio-streams
    chmod: '755'
  f_flameshot_config:
    src: config/flameshot/flameshot.ini
    dst: ~/.config/flameshot/flameshot.ini
  f_get-iommu-groups:
    src: local/bin/get-iommu-groups
    dst: ~/.local/bin/get-iommu-groups
    chmod: '755'
  f_gitconfig:
    src: config/git/config
    dst: ~/.config/git/config
  f_htoprc:
    src: config/htop/htoprc
    dst: ~/.config/htop/htoprc
  f_hypr-fixworkspaces:
    src: local/bin/hypr-fixworkspaces
    dst: ~/.local/bin/hypr-fixworkspaces
    chmod: '744'
  f_hypr-monitorctl:
    src: local/bin/hypr-monitorctl
    dst: ~/.local/bin/hypr-monitorctl
    chmod: '744'
  f_hyprsunset.conf:
    src: config/hypr/hyprsunset.conf
    dst: ~/.config/hypr/hyprsunset.conf
  f_index.theme:
    src: icons/default/index.theme
    dst: ~/.icons/default/index.theme
  f_kanshi_config:
    src: config/kanshi/config
    dst: ~/.config/kanshi/config
  f_keepassxc.ini:
    src: config/keepassxc/keepassxc.ini
    dst: ~/.config/keepassxc/keepassxc.ini
  f_kitty.conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_kvantum.kvconfig:
    src: config/Kvantum/kvantum.kvconfig
    dst: ~/.config/Kvantum/kvantum.kvconfig
  f_lutris.conf:
    src: config/lutris/lutris.conf
    dst: ~/.config/lutris/lutris.conf
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
    chmod: '600'
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_pavucontrol.ini:
    src: config/pavucontrol.ini
    dst: ~/.config/pavucontrol.ini
  f_plug.vim:
    src: vim/autoload/plug.vim
    dst: ~/.vim/autoload/plug.vim
  f_prusaslicer.ini:
    src: config/PrusaSlicer/PrusaSlicer.ini
    dst: ~/.config/PrusaSlicer/PrusaSlicer.ini
  f_prusaslicergcodeviewer.ini:
    src: config/PrusaSlicer/PrusaSlicerGcodeViewer.ini
    dst: ~/.config/PrusaSlicer/PrusaSlicerGcodeViewer.ini
  f_pythonrc:
    src: config/python/pythonrc
    dst: ~/.config/python/pythonrc
  f_qbittorrent.conf:
    src: config/qBittorrent/qBittorrent.conf
    dst: ~/.config/qBittorrent/qBittorrent.conf
  f_reload.sh:
    src: config/hypr/scripts/reload.sh
    dst: ~/.config/hypr/scripts/reload.sh
    chmod: '744'
  f_setup-pipewire-nodes:
    src: local/bin/setup-pipewire-nodes
    dst: ~/.local/bin/setup-pipewire-nodes
    chmod: '755'
  f_shell:
    src: shell
    dst: ~/.shell
  f_sunsetr.toml:
    src: config/sunsetr/sunsetr.toml
    dst: ~/.config/sunsetr/sunsetr.toml
  f_swappy_config:
    src: config/swappy/config
    dst: ~/.config/swappy/config
  f_uca.xml:
    src: config/Thunar/uca.xml
    dst: ~/.config/Thunar/uca.xml
    chmod: '600'
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_xsettingsd.conf:
    src: config/xsettingsd/xsettingsd.conf
    dst: ~/.config/xsettingsd/xsettingsd.conf
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
profiles:
  mia:
    dotfiles:
      - f_shell
      - f_bashrc
      - d_zsh
      - f_zshenv
      - d_oh-my-zsh
      - f_p10k.zsh
      - f_gitconfig
      - f_dmrc
      - d_btop
      - d_gtk-2.0
      - d_gtk-3.0
      - f_htoprc
      - d_hypr
      - f_keepassxc.ini
      - f_kitty.conf
      - f_kvantum.kvconfig
      - f_lutris.conf
      - f_config.conf
      - d_config_oh-my-zsh_plugins
      - d_config_oh-my-zsh_themes
      - d_local_share_ulauncher_extensions
      - f_prusaslicer.ini
      - f_prusaslicergcodeviewer.ini
      - f_pythonrc
      - d_qt5ct
      - d_ranger
      - f_config
      - f_config.json
      - f_uca.xml
      - d_waybar
      - d_xfce4
      - f_code-flags.conf
      - f_electron-flags.conf
      - f_electron13-flags.conf
      - f_mimeapps.list
      - f_pavucontrol.ini
      - f_index.theme
      - d_openrgb
      - d_rofi
      - d_systemd
      - d_ulauncher
      - d_ulauncher_themes
      - f_vimrc
      - f_plug.vim
      - d_plugged
      - d_blender
      - d_mpv
      - f_qbittorrent.conf
      - f_xsettingsd.conf
      - f_flameshot_config
      - f_swappy_config
      - d_gtklock
      - f_get-iommu-groups
      - f_setup-pipewire-nodes
      - f_extract-audio-streams
      - d_wofi
      - f_hypr-monitorctl
      - f_hypr-fixworkspaces
      - f_kanshi_config
      - f_hyprsunset.conf
      - f_reload.sh
      - f_sunsetr.toml
